# Generated by Django 5.1 on 2024-08-29 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('creation_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('team_leader', 'Team Leader')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('australian_sailing_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('membership_category', models.CharField(choices=[('Senior sailing membership', 'Senior sailing membership – A senior sailor is any member over the age of 18 with full member privileges'), ('Senior crew membership', 'Senior crew membership – A senior crew is any member over the age of 18 but does not own a boat within the club'), ('Junior sailing membership', 'Junior sailing membership – Any sailing member under the age of 18'), ('Family membership', 'Family membership – This membership is for families consisting of two adult members over the age of 18 with dependents under the age of 18'), ('Non sailing membership', 'Non sailing membership – for members that want to be part of the club that do not sail a boat'), ('Provisional Membership', 'Provisional Membership – A person who is a full member of a kindred water sports club'), ('Pensioner/Student', 'Pensioner/Student – (see concession information below)')], max_length=50)),
                ('will_volunteer_or_pay_levy', models.CharField(blank=True, choices=[('I will volunteer', 'I will volunteer'), ('I will pay the levy', 'I will pay the levy')], max_length=50, null=True)),
                ('teams', models.ManyToManyField(blank=True, related_name='members', to='events.team')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('on_water', 'On-Water'), ('off_water', 'Off-Water')], max_length=10)),
                ('date', models.DateField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.user')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('hours', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.user')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.teammember')),
            ],
        ),
    ]
