# Generated by Django 5.1 on 2024-08-20 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='membership_category',
            field=models.CharField(choices=[('Senior sailing membership', 'Senior sailing membership – A senior sailor is any member over the age of 18 with full member privileges'), ('Senior crew membership', 'Senior crew membership – A senior crew is any member over the age of 18 but does not own a boat within the club'), ('Junior sailing membership', 'Junior sailing membership – Any sailing member under the age of 18'), ('Family membership', 'Family membership – This membership is for families consisting of two adult members over the age of 18 with dependents under the age of 18'), ('Non sailing membership', 'Non sailing membership – for members that want to be part of the club that do not sail a boat'), ('Provisional Membership', 'Provisional Membership – A person who is a full member of a kindred water sports club'), ('Pensioner/Student', 'Pensioner/Student – (see concession information below)')], max_length=50),
        ),
    ]
