# Generated by Django 5.1 on 2024-09-02 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_user_groups_remove_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='activities',
            field=models.ManyToManyField(blank=True, related_name='events', to='events.activity'),
        ),
        migrations.AddField(
            model_name='volunteerpoints',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.activity'),
        ),
    ]
