# Generated by Django 5.1 on 2024-09-05 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='team',
            name='team_leader',
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
