# Generated by Django 5.1 on 2024-10-02 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.team'),
        ),
    ]
