# Generated by Django 5.1 on 2024-10-04 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_event_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='mobile',
            field=models.CharField(max_length=20),
        ),
    ]
