# Generated by Django 5.1 on 2024-10-08 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_alter_event_created_by_alter_event_team_and_more'),
        ('events', '0016_alter_teammember_mobile'),
    ]

    operations = [
    ]
