# Generated by Django 5.1 on 2024-08-31 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('australian_sailing_number', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(max_length=100)),
                ('volunteer_levy', models.CharField(blank=True, choices=[('I will volunteer', 'I will volunteer'), ('I will pay the levy', 'I will pay the levy'), ('', 'Blank')], max_length=50, null=True)),
                ('volunteer_teams', models.ManyToManyField(blank=True, to='upload_csv.volunteerteam')),
            ],
        ),
    ]
