# Generated by Django 5.1 on 2024-08-31 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteerteam',
            old_name='team_name',
            new_name='name',
        ),
    ]
