# Generated by Django 5.1 on 2024-09-03 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_csv', '0002_rename_team_name_volunteerteam_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='VolunteerTeam',
        ),
    ]
